/*      CREACION BACK SISTEMA DE ENVÍOS*/
CREATE TABLE JESUSECM21/PRODUCTOS                                   
(IDPRO INTEGER not null GENERATED ALWAYS AS IDENTITY (START WITH 1 
INCREMENT BY 1),
IDCAT INTEGER,                                                   
PRODUCTO CHAR (30) NOT NULL WITH DEFAULT, 
PREUNIT DEC (12) NOT NULL WITH DEFAULT,
PRSTOCK INTEGER, 
FECHAC DATE NOT NULL WITH DEFAULT,
ACTIVO CHAR(1)NOT NULL WITH DEFAULT) 

CREATE TABLE JESUSECM21/CATEGORIAS                                   
(IDCAT INTEGER not null GENERATED ALWAYS AS IDENTITY (START WITH 1 
INCREMENT BY 1),                                                   
CATEGORIA CHAR (30) NOT NULL WITH DEFAULT, 
FECHAC DATE NOT NULL WITH DEFAULT, 
SEXO CHAR (1) NOT NULL WITH DEFAULT)

CREATE TABLE JESUSECM21/CLIENTE                                   
(IDCL INTEGER not null GENERATED ALWAYS AS IDENTITY (START WITH 1 
INCREMENT BY 1),
CEDULA CHAR (15) NOT NULL,                                                   
NOMBRE CHAR (30) NOT NULL WITH DEFAULT,
APELLIDO CHAR (30) NOT NULL WITH DEFAULT,  
FECHAN DATE NOT NULL WITH DEFAULT, 
SEXO CHAR (1) NOT NULL WITH DEFAULT)

CREATE TABLE JESUSECM21/ENVIOS                                   
(IDEN INTEGER not null GENERATED ALWAYS AS IDENTITY (START WITH 1 
INCREMENT BY 1),                                                   
IDCL INTEGER NOT NULL WITH DEFAULT, 
PESO dec(5),
PAIS CHAR (56),
DIRECCION Char(150),
CODIGOP CHAR(8),
METODOENV CHAR(1),
FECHAC DATE NOT NULL WITH DEFAULT, 
FECHAS DATE, 
FECHAR DATE) 
/*METODOENV =  'A' = AEREO  | 'M' = MARÍTIMO | 'T'=TERRESTRE*/
/* FECHAC = Fecha de creación de registro*/
/* FECHAS = Fecha de envío de paquete*/
/* FECHAR = Fecha de requerimiento de productos*/

CREATE TABLE JESUSECM21/ENVIODS
(IDEN INTEGER not null,                                                   
IDPR INTEGER NOT NULL WITH DEFAULT, 
PREUNIT DEC(12) NOT NULL WITH DEFAULT, 
CANTIDAD INTEGER,
DESCUENTO DEC(10))

/************************************************ USUARIOS *****************************/
CREATE TABLE JESUSECM21/USUARIOS
(IDUSR INTEGER not null GENERATED ALWAYS AS IDENTITY (START WITH 1 
INCREMENT BY 1),
USERNAME CHAR(30)not null,
EMAIL CHAR(100) not null,
PASS CHAR(60),
INTENTOS INTEGER,
BLOQUEADO BOOLEAN,
LOGGER BOOLEAN,
ACTIVE BOOLEAN
ROL char(1))

/***********************************SEGURIDAD USUARIOS***************************************/
CREATE TABLE JESUSECM21/SECUUSER
(IDUSR INTEGER,
PGN1 CHAR(20),
RPN1 CHAR(20),
PGN2 CHAR(20),
RPN2 CHAR(20),
PGN3 CHAR(20),
RPN3 CHAR(20)
)

/********************************************** TEXTOS ************************************/

CREATE TABLE JESUSECM21/TEXTOS
(IDTXT INTEGER not null,
LENGUAJE CHAR(2),
TEXTO CHAR(200))